test:
  stage: test
  image: python:3.9-bullseye
  script:
    - pip install .
    - pip install pytest pytest-cov
    - python -c "import qbm"
    - python -c "import qbm.metrics"
    - python -c "import qbm.plotting"
    - python -c "import qbm.sampling"
    - python -c "import qbm.utils"
    - python -c "import qbm.models"
    - pytest --cov-report=term-missing --cov=qbm --cov-config=.coveragerc
    - coverage xml
  coverage: '/TOTAL.*\s+(\d+\%)/'
pages:
  stage: deploy
  image: python:3.9-bullseye
  script:
    - pip install .
    - pip install Sphinx sphinx_rtd_theme m2r2 anybadge
    - sphinx-apidoc -f -o docs/source src/qbm
    - sphinx-build -d docs/_build/doctrees docs/source docs/_build/html
    - mv docs/_build/html public
    - anybadge --value=master --file=docs.svg --label=docs --color=#0f80c0
    - anybadge --value=master --file=report.svg --label=report --color=#008080
  artifacts:
    expire_in: 1 week
    paths:
      - public
      - docs.svg
      - report.svg
report:
  stage: deploy
  image: texlive/texlive:TL2021-historic
  script:
    - cd latex/report
    - latexmk -pdf main.tex
  artifacts:
    expire_in: 1 week
    paths:
      - latex/report/main.pdf
