image: python:3.9-bullseye
build:
  stage: build
  script:
    - pip install .
    - python -c "import qbm"
    - python -c "import qbm.metrics"
    - python -c "import qbm.plotting"
    - python -c "import qbm.sampling"
    - python -c "import qbm.utils"
test:
  stage: test
  script:
    - pip install .
    - pip install pytest pytest-cov
    - pytest
    - coverage xml
  artifacts:
    reports:
      cobertura: coverage.xml
