name: qbm
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - black
  - flake8
  - ipython
  - ipykernel
  - jupyterlab
  - matplotlib=3.4.3
  - mplfinance=0.12.7a17
  - numba=0.54.1
  - numpy=1.20.3
  - pandas=1.3.3
  - pip
  - scikit-learn=0.24.2
  - scikit-learn-intelex=2021.3.0
  - scipy==1.7.1
  - pip:
    - dwave-ocean-sdk
    - jupyterlab_code_formatter
    - jupyterlab_vim
    - pandas-market-calendars==3.2
