name: qbm
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - cython=0.29.24
  - matplotlib=3.4.3
  - mplfinance=0.12.7a17
  - numba=0.54.1
  - numpy=1.20.3
  - pandas=1.3.3
  - pip
  - scipy=1.7.1
  - seaborn=0.11.2
  - statsmodels=0.12.2
  - tqdm=4.62.3
  - pip:
    - dwave-ocean-sdk==4.2.0
    - emcee==3.1.1
    - pandas-market-calendars==3.2
