name: qbm
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.9
  - black
  - flake8
  - ipython
  - ipython-autotime
  - ipykernel
  - jupyterlab
  - matplotlib=3.4.3
  - mplfinance=0.12.7a17
  - numba=0.54.1
  - numpy=1.20.3
  - pandas=1.3.3
  - pip
  - scipy=1.7.1
  - statsmodels=0.12.2
  - pip:
    - dwave-ocean-sdk==4.2.0
    - emcee==3.1.1
    - jupyterlab_code_formatter
    - jupyterlab_vim
    - pandas-market-calendars==3.2
    - "git+https://github.com/cameronperot/scikit-learn.git#egg=scikit-learn"
